/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: [
      'www.solis-srbija.rs',
      'www.agrovojvodina-mehanizacija.co.rs',
      'www.ursus.com',
      'poljomarket.rs',
      'www.celmak.com',
      'www.tafe.com',
      'mahindratractor.com',
      'www.deere.rs',
      'zetor.com',
      'yumetal.rs',
      'www.deere.com',
      'www.deere.com.au',
      'www.agro-simeks.com',
      'www.belarus-tractor.com',
      'www.carrarotractors.com',
      'www.fpm.rs',
      'bell-impex.rs',
      'majevica.co.rs',
      'agrotrade.rs',
      'www.agrokompleks.rs',
      'www.morava.co',
      'www.gumaplast-rau.rs',
      'ormaric.com',
      'www.minosagri.com',
      'www.agroferocoop.rs',
      'www.gorenc.si',
      'www.sip.si',
      'www.inobrezice.com',
      'www.megametal.hr',
      'jugometal.co.rs',
      'firebasestorage.googleapis.com',
    ],
  },
}

module.exports = nextConfig
