import Head from 'next/head'
import Image from 'next/image'

import MainLayout from '../layout/MainLayout'

import HomeBanner from '../components/Banners/HomeBanner'
import Logo from '../components/Logo'
import LandingMoto from '../components/Moto/LandingMoto'
import FrontCategories from '../components/FrontCategories'
import Test from '../components/Featured/test'
import { fetchFeatured } from '../lib/data'
import Featured from '../components/Featured'

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Jugometal</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainLayout>
        <Logo />
        <HomeBanner />
        <LandingMoto />
        <FrontCategories />

        <Featured data={data} />
      </MainLayout>
    </div>
  )
}

// getstaticprops
export const getStaticProps = async () => {
  const data = await fetchFeatured()

  return {
    props: {
      data,
    },
  }
}
